import { Call, Events } from '@wailsio/runtime';

const appCall = (name: string, ...args: any[]) => Call.ByName(`main.App.${name}`, ...args);

export const EventsOn = (eventName: string, callback: (data: any) => void) =>
  Events.On(eventName, (event) => callback(event.data));

export const GetAutoStart = () => appCall('GetAutoStart');
export const SetAutoStart = (enabled: boolean) => appCall('SetAutoStart', enabled);
export const GetShowMainWindowOnAutoStart = () => appCall('GetShowMainWindowOnAutoStart');
export const SetShowMainWindowOnAutoStart = (enabled: boolean) => appCall('SetShowMainWindowOnAutoStart', enabled);
export const GetAutoEnableProxyOnAutoStart = () => appCall('GetAutoEnableProxyOnAutoStart');
export const SetAutoEnableProxyOnAutoStart = (enabled: boolean) => appCall('SetAutoEnableProxyOnAutoStart', enabled);
export const GetLanguage = () => appCall('GetLanguage');
export const SetLanguage = (lang: string) => appCall('SetLanguage', lang);
export const GetTheme = () => appCall('GetTheme');
export const SetTheme = (theme: string) => appCall('SetTheme', theme);
export const GetTUNConfig = () => appCall('GetTUNConfig');
export const UpdateTUNConfig = (cfg: any) => appCall('UpdateTUNConfig', cfg);
export const GetTUNStatus = () => appCall('GetTUNStatus');
export const StartTUN = () => appCall('StartTUN');
export const StopTUN = () => appCall('StopTUN');
export const AddSiteGroup = (sg: any) => appCall('AddSiteGroup', sg);
export const AddUpstream = (u: any) => appCall('AddUpstream', u);
export const ClearLogs = () => appCall('ClearLogs');
export const DeleteECHProfile = (id: string) => appCall('DeleteECHProfile', id);
export const DeleteSiteGroup = (id: string) => appCall('DeleteSiteGroup', id);
export const DeleteUpstream = (id: string) => appCall('DeleteUpstream', id);
export const DisableSystemProxy = () => appCall('DisableSystemProxy');
export const EnableSystemProxy = () => appCall('EnableSystemProxy');
export const ExportCert = () => appCall('ExportCert');
export const ExportConfig = () => appCall('ExportConfig');
export const FetchECHConfig = (domain: string, dohURL: string) => appCall('FetchECHConfig', domain, dohURL);
export const ForceFetchCloudflareIPs = () => appCall('ForceFetchCloudflareIPs');
export const GetCACertPEM = () => appCall('GetCACertPEM');
export const GetCACertPath = () => appCall('GetCACertPath');
export const GetCAInstallStatus = () => appCall('GetCAInstallStatus');
export const GetCloseToTray = () => appCall('GetCloseToTray');
export const GetCloudflareConfig = () => appCall('GetCloudflareConfig');
export const GetCloudflareIPStats = () => appCall('GetCloudflareIPStats');
export const GetECHProfiles = () => appCall('GetECHProfiles');
export const GetInstalledCerts = () => appCall('GetInstalledCerts');
export const IsLogCaptureEnabled = () => appCall('IsLogCaptureEnabled');
export const GetListenPort = () => appCall('GetListenPort');
export const GetProxyDiagnostics = () => appCall('GetProxyDiagnostics');
export const GetProxyMode = () => appCall('GetProxyMode');
export const GetRecentLogs = (limit: number) => appCall('GetRecentLogs', limit);
export const GetServerConfig = () => appCall('GetServerConfig');
export const GetSiteGroups = () => appCall('GetSiteGroups');
export const GetStats = () => appCall('GetStats');
export const GetSystemProxyStatus = () => appCall('GetSystemProxyStatus');
export const GetUpstreams = () => appCall('GetUpstreams');
export const Greet = (name: string) => appCall('Greet', name);
export const HandleWindowClose = () => appCall('HandleWindowClose');
export const ImportConfig = (content: string) => appCall('ImportConfig', content);
export const ImportConfigWithSummary = (content: string) => appCall('ImportConfigWithSummary', content);
export const InstallCA = () => appCall('InstallCA');
export const IsProxyRunning = () => appCall('IsProxyRunning');
export const OpenCAFile = () => appCall('OpenCAFile');
export const OpenCertDir = () => appCall('OpenCertDir');
export const ProxySelfCheck = () => appCall('ProxySelfCheck');
export const QuitApp = () => appCall('QuitApp');
export const RefreshCloudflareIPPool = () => appCall('RefreshCloudflareIPPool');
export const RegenerateCert = () => appCall('RegenerateCert');
export const RemoveInvalidCFIPs = () => appCall('RemoveInvalidCFIPs');
export const SetCloseToTray = (enabled: boolean) => appCall('SetCloseToTray', enabled);
export const SetListenPort = (port: number) => appCall('SetListenPort', port);
export const SetProxyMode = (mode: string) => appCall('SetProxyMode', mode);
export const StartLogCapture = () => appCall('StartLogCapture');
export const StartProxy = () => appCall('StartProxy');
export const StopLogCapture = () => appCall('StopLogCapture');
export const StopProxy = () => appCall('StopProxy');
export const TriggerCFHealthCheck = () => appCall('TriggerCFHealthCheck');
export const UninstallCert = (thumbprint: string) => appCall('UninstallCert', thumbprint);
export const UpdateCloudflareConfig = (cfg: any) => appCall('UpdateCloudflareConfig', cfg);
export const UpdateServerConfig = (host: string, auth: string) => appCall('UpdateServerConfig', host, auth);
export const UpdateSiteGroup = (sg: any) => appCall('UpdateSiteGroup', sg);
export const UpdateTrayMenu = () => appCall('UpdateTrayMenu');
export const UpdateUpstream = (u: any) => appCall('UpdateUpstream', u);
export const UpsertECHProfile = (p: any) => appCall('UpsertECHProfile', p);
export const WindowClose = () => appCall('WindowClose');
export const WindowMinimise = () => appCall('WindowMinimise');
export const WindowToggleMaximise = () => appCall('WindowToggleMaximise');
export const GetAutoRoutingConfig = () => appCall('GetAutoRoutingConfig');
export const UpdateAutoRoutingConfig = (cfg: any) => appCall('UpdateAutoRoutingConfig', cfg);
export const GetAutoRoutingStatus = () => appCall('GetAutoRoutingStatus');
export const RefreshGFWList = () => appCall('RefreshGFWList');
export const TestServerNode = () => appCall('TestServerNode');

// DNS Node API
export const GetDNSNodes = () => appCall('GetDNSNodes');
export const AddDNSNode = (n: any) => appCall('AddDNSNode', n);
export const UpdateDNSNode = (n: any) => appCall('UpdateDNSNode', n);
export const DeleteDNSNode = (id: string) => appCall('DeleteDNSNode', id);
export const SetDNSNodePriority = (id: string, targetIndex: number) => appCall('SetDNSNodePriority', id, targetIndex);
export const TestDNSNode = (nodeID: string) => appCall('TestDNSNode', nodeID);

// Update Management API
export const CheckUpdate = () => appCall('CheckUpdate');
export const StartUpdate = () => appCall('StartUpdate');
